
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  adapter: postgresql
  host: localhost
  database: FriendlyDev
  username: ryanwong


test:
  <<: *default
  database: Friendly_test


production:
  <<: *default
  database: Friendly_production
  username: Friendly
  password: <%= ENV['FRIENDLY_DATABASE_PASSWORD'] %>
